### PR TITLE
Add disc age #569

### PR DESCRIPTION
**Pull request by Rick-Methot-NOAA**
resolves issue #569 

## Concisely describe what has been changed/addressed in the pull request.
add output of discard_at_age for forecast years

## What tests have been done? 
visual exam of report.sso shows that discard_at-age now appears for forecast years

### CODE REVIEW

**Review by iantaylor-NOAA — APPROVED** [review]
Changes look good to me.
It might be worth waiting until the workflows are sorted out before merging to confirm that the tests pass.

**Comment by Rick-Methot-NOAA** [comment]
@e-perl-NOAA   help please.

**Comment by e-perl-NOAA** [comment]
Probably has to deal with the merge conflicts with the recent push of the makefile updates. Will rebase tomorrow morning.

**Comment by e-perl-NOAA** [comment]
@Rick-Methot-NOAA this should be good to merge now

**Pull request merged**
