### PR TITLE
Warning action update

### PR DESCRIPTION
**Pull request by e-gugliotti-NOAA**
## Concisely describe what has been changed/addressed in the pull request.

Update build-ss3-warnings.yml to compare to a reference warnings file and fail if the number of warnings from a new build is greater than the number of warnings in that reference warnings file.

* Resolves issue #452 

### Where are the relevant files?

- [x] No test files are required for this pull request. -->

### What tests/review still need to be done?

None.

## Is there an input change for users to Stock Synthesis? 

- [x] No, there was no input change. -->

### CODE REVIEW

**Review by Rick-Methot-NOAA — DISMISSED** [review]
looks good

**Comment by iantaylor-NOAA** [comment]
This is great, thank you @e-gugliotti-NOAA.

Is it worth making a plan for when to update the .github/workflows/reference_files/warnings_ss_ref.txt file?
I can think of at least 2 scenarios:
* If the github action fails due to an increase in length of the warnings files, and we can't make the new warning go away but decide it can be ignored, then we would want to update the reference file to account for the increased length. 
* Any time a warning goes away we would also want to update the file to make sure future new warnings get detected.
 
Would it be worth supplementing the `if (n_warn > length(ref))` to with a separate failing message when ``if (n_warn < length(ref))` to help us see when the second scenario occurs? Maybe that's not needed since the change that makes the warning go away is probably some change that we're making to achieve that end and won't just happen by accident.

**Comment by e-gugliotti-NOAA** [comment]
@iantaylor-NOAA I added lines similar to what you suggested. The R code written by Kathryn originally to get the n_warn only detects true warnings, so it isn't detecting the 2 lines that say "In file included from ss.cpp:7:" currently in the reference warnings text file, which is why the code has `if(n_warn+length(ref) > length(ref))`. Could you add your review?

**Review by iantaylor-NOAA — APPROVED** [review]
Good catch with the 2 lines that we're ignoring.

**Pull request merged**
