### PR TITLE
Unify F approach

### PR DESCRIPTION
**Pull request by Rick-Methot-NOAA**
continues development for issue #570  and especially #581
See description and example in #581
Substantial refactoring of the internal machinery for managing F as parameter vs F as hybrid
extends the F-detail approach previously available only for F_method 2 to F_method 4

only new input is for F_method 4 if using the F_detail feature.

### CODE REVIEW

**Comment by e-perl-NOAA** [comment]
Okay so the spinydogfish model echoinput file is stopping after:
```
GP Seas Area Use? female_recr_dist
1 1 1 1 0.5
 made the age_age' key 
Finished evaluating biology calculations once


Begin estimating
```

Warning file looks like the following:
```
Note 1 Information: Max data length bin: 132  < max pop len bins: 136; so will accumulate larger pop len bins
3 iter 1
 hrate for 1970: 
```

**Comment by Rick-Methot-NOAA** [comment]
that stop in dogfish might only be because I had not yet removed a specific output statement while debugging.  It is gone now.

**Comment by e-perl-NOAA** [comment]
Yes, all seems to be working!

**Review by iantaylor-NOAA — APPROVED** [review]
Looks good. I didn't try to follow all the details, but I don't see any red flags. The tests are all passing, including the vermillion_snapper_F4 model which uses F Method 4. 

I compared Report files and see the DISCARD_AT_AGE is now available in the forecast as intended (discussed in #569). 
image

I see control.ss_new remains the same except for improved comments
image

**Comment by Rick-Methot-NOAA** [comment]
Thanks Ian.  Nothing magic about the 2.9 value.  The role of max F is mostly to keep model from exploring F levels that nearly extirpate older fish.  In the attached example, it is constraining during early hybrid phases to keep F below 2.9, which creates a catch penalty, which moves model back to higher biomass and lower F values.  For long-lived stocks a maxF of 0.4 might seem reasonable, but even 0.40 will not extirpate.

**Pull request merged**
