### PR TITLE
issue 646 - fix output error in Index_2, plus two minor output tweaks

### PR DESCRIPTION
**Pull request by Rick-Methot-NOAA**
## Concisely describe what has been changed/addressed in the pull request.

fixes output error in Index_2 that was introduced with Qtype 6.

* Resolves issue #646 

### Where are the relevant files?

 [x] Test files are in the issue. 

### What tests/review still need to be done?

None
## Is there an input change for users to Stock Synthesis? 

[x] No, there was no input change.

### CODE REVIEW

**Review by iantaylor-NOAA — APPROVED** [review]
The changes look good to me. Thanks for fixing the issue so quickly.

The "Q" to "Qbase" change wasn't the issue for r4ss, rather the logic for parsing the INDEX_2 table wasn't adaptable to the additional comment line (unlike most other tables). I think I fixed the r4ss issue on the second try and just restarted the failed github action for the second time. If it passes the check (should be done in about 15 minutes) I think it's fine to merge.

**Comment by iantaylor-NOAA** [comment]
The `test-r4ss-with-ss3` check is now passing, so I think this is fine to merge.

@e-perl-NOAA do you know why `build-ss3` was skipped?

@Rick-Methot-NOAA, do you think this bug needs a bug-fix release? It seems like users interested in Q_type 3 = power (+1 parm) which is causing the error fixed by this PR. could temporarily use type 6=offset & power (+2p) with the offset parameter fixed at 0 and get all the functionality of type 3. If we announced that solution on the forum we could potentially avoid a bug fix release and just wait until other features are ready for a bigger release.

**Comment by Rick-Methot-NOAA** [comment]
I thought the same Ian.  Let's do a bug fix release for this one.

**Comment by e-perl-NOAA** [comment]
I have no idea why it was skipped, but I'm running it [here](https://github.com/nmfs-ost/ss3-source-code/actions/runs/12144400962)

**Comment by Rick-Methot-NOAA** [comment]
Let's do both a big fix and a message in the Forum.  The Forum message can serve to advertise the availability of the offset approach.

**Comment by iantaylor-NOAA** [comment]
Sounds good.
A bug fix release has the additional benefit that we can test whether the linux and mac versions continue to have issues with missing libraries when run in those same platforms on github actions (necessitating an extra setup step to add the libraries as @e-perl-NOAA did at https://github.com/nmfs-ost/ss3-user-examples/commit/7173d5e83ffde4f3c9d04e44c6cf91bd3067cfd1).

**Comment by e-perl-NOAA** [comment]
Sounds good!

**Pull request merged**
