### PR TITLE
Admb docker images

### PR DESCRIPTION
**Pull request by e-perl-NOAA**
## Concisely describe what has been changed/addressed in the pull request.

* Resolves issue #

### CODE REVIEW

**Comment by e-perl-NOAA** [comment]
@Rick-Methot-NOAA and @johnoel can you look at the build-ss3.yml and see why there are those errors? Just created a draft PR because it's easier to see the testing in a PR than just on a branch.

**Comment by Rick-Methot-NOAA** [comment]
I see the code successfully pulling from johnoel/admb-linux and then failing to build it for a C++ reason that should not be occurring.  Later when it tries for windows, it cannot connect to:  johnoel/admb-windows.
Wish I knew enough to help more.

**Comment by e-perl-NOAA** [comment]
@Rick-Methot-NOAA I couldn't tell if it was a C++/ss3 issue with linux, but yes, with windows the admb docker still isn't working.

**Comment by Rick-Methot-NOAA** [comment]
Do we need to reach out to additional people who have docker experience?  perhaps in the R user group or the FIMS team?

**Comment by johnoel** [comment]
I will check on this now...

**Comment by johnoel** [comment]
Running the ADMB Docker container within a GitHub Action container is most likely the issue.  Using the ADMB Docker on a local host works just fine.

**Comment by e-perl-NOAA** [comment]
the linux and mac images did work until rebasing my branch and adding the changes from the recent commit. The windows image never worked so that might be a github action issue.

**Comment by johnoel** [comment]
Okay, I'll try again

**Comment by e-perl-NOAA** [comment]
I just created a new branch from main and added your changes in there in case the issue was the result of a merge conflict. The branch is admb-docker-attempt2 if you look in the actions tab to see how those run. I decided to just comment out the windows image and focus on the linux and mac images at least for now since I know at one point those worked.

**Comment by johnoel** [comment]
See Pull Request #552

**Comment by e-perl-NOAA** [comment]
Closing because testing on a different branch and will make a new PR to use admb docker image in other workflows when ready.

**Pull request closed without merging**
