### PR TITLE
Add bootstrap workflow

### PR DESCRIPTION
**Pull request by e-perl-NOAA**
## Concisely describe what has been changed/addressed in the pull request.

Add workflow to test bootstrap files. Will need to wait on this until the PR to add Simple_with_DM_sizefreq has gone through in the test models repo.

### Where are the relevant files?

- [x] No test files are required for this pull request. -->

### What tests/review still need to be done?

Local testing plus test workflow with push.

## Is there an input change for users to Stock Synthesis? 

- [x] No, there was no input change. -->

### CODE REVIEW

**Comment by iantaylor-NOAA** [comment]
@e-perl-NOAA, I see this is marked as "Draft", but I took a look anyway and it looks good to me. 
It would be good to see it in action, but maybe merging the change is the easiest way to do that. 
To see the output from the `message()` commands, would you just look at the log of the github action? It looks like there's no artifact created, which is fine.

**Comment by e-perl-NOAA** [comment]
Yes, I have it as a draft just because I didn't know if there were any more tests that you could think of that we should add. No artifacts are created. I did run the action from the branch which you can see [here](https://github.com/nmfs-ost/ss3-source-code/actions/runs/7351025171).

**Comment by iantaylor-NOAA** [comment]
Thanks @e-perl-NOAA. The messages in the action run on the branch are easy to follow, but as you say they can be ignored if the action is passing. I can't think of any additional tests, so I would just merge this one and we can always add more in the future if we think of anything.

**Review by iantaylor-NOAA — DISMISSED** [review]

**Comment by e-perl-NOAA** [comment]
@iantaylor-NOAA testing if GitHub support's suggestion of closing the PR and re-opening will allow you to re-review when a commit is made after an approval

**Review by iantaylor-NOAA — APPROVED** [review]
Looks good. Testing if this review after close/open works.

**Comment by e-perl-NOAA** [comment]
Okay great! At least the suggestion from the GitHub support team works to get around the bug!

**Pull request merged**
