### PR TITLE
change repo name to ss3-source-code

### PR DESCRIPTION
**Pull request by e-gugliotti-NOAA**
## Concisely describe what has been changed/addressed in the pull request.

This is changing all the repo names in preparation for migration to GHEC:
stock-synthesis -> ss3-source-code
doc -> ss3-doc
user-examples -> ss3-user-examples
test-models -> ss3-test-models

### Where are the relevant files?

- [x] No test files are required for this pull request.

### What tests/review still need to be done?

None.

## Is there an input change for users to Stock Synthesis? 

- [x] No, there was no input change.

## Additional information (optional).

You will see pull requests like this across the nmfs-stock-synthesis org and a PR in r4ss.

### CODE REVIEW

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA can you review this really quick so that I can go ahead and merge in the name changes?

**Review by iantaylor-NOAA — APPROVED** [review]
Looks good.
Thank you @e-gugliotti-NOAA!

**Review by iantaylor-NOAA — APPROVED** [review]

**Review by iantaylor-NOAA — APPROVED** [review]

**Review by iantaylor-NOAA — DISMISSED** [review]

**Comment by Rick-Methot-NOAA** [comment]
looking good Elizabeth.  Thanks for reviewing Ian.

**Comment by e-gugliotti-NOAA** [comment]
@Rick-Methot-NOAA can you approve this? for some reason it's not allowing Ian's review to count and I'm not sure why. I've messaged Dave but he's not answering.

**Review by Rick-Methot-NOAA — APPROVED** [review]
trusting all is good.

**Review by iantaylor-NOAA — DISMISSED** [review]

**Review by Rick-Methot-NOAA — APPROVED** [review]
reviewed

**Pull request merged**
